services:
  backend:
    build:
      context: ./kloop_back
      dockerfile: dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./kloop_front
      dockerfile: dockerfile
    ports:
      - "3000:3000"
