global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: "flask_app"
    metrics_path: "/metrics"  # Specify the metrics path here
    static_configs:
      - targets:
          - "backend:5000" 